# Generated by Django 3.2.4 on 2021-11-01 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advisor_name', models.CharField(max_length=30)),
                ('Advisor_image', models.ImageField(blank=True, default='post-default.jpg', null=True, upload_to='advisor/profile_images')),
                ('Advisor_client', models.CharField(default='None', max_length=20)),
                ('Booking_Id', models.SlugField(blank=True, default='Not_Booked', null=True)),
                ('Booking_Time', models.CharField(default=django.utils.timezone.now, max_length=100)),
            ],
        ),
    ]
