# Generated by Django 3.2.4 on 2021-11-01 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='Booking_Time',
            field=models.CharField(default=django.utils.timezone.now, help_text='format -> YYYY-MM-DD HH:MM:SS', max_length=100),
        ),
    ]
